task: detection

num_classes: 5
remap_mscoco_category: True

train_dataloader: 
  type: DataLoader
  dataset: 
    type: CocoRDetection
    img_folder: /data1/xiaoyiming/datasets/DroneVehicle/train/trainimgr
    ann_file: /data1/xiaoyiming/datasets/DroneVehicle/train/train_ir_1.json
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  batch_size: 8
  num_workers: 4
  drop_last: True


val_dataloader:
  type: DataLoader
  dataset: 
    type: CocoRDetection
    img_folder: /data1/xiaoyiming/datasets/DroneVehicle/val/valimgr
    ann_file: /data1/xiaoyiming/datasets/DroneVehicle/val/val_ir_1.json
    transforms:
      type: Compose
      ops: ~ 

  shuffle: False
  batch_size: 8
  num_workers: 8
  drop_last: False
